interface Box {
  type: string;
  body: number;
  end: number;
  start: number;
}

interface Sample extends EncodedVideoChunkInit {
  data: Uint8Array<ArrayBuffer>;
  decodeTime: number;
  config: VideoDecoderConfig;
}

function boxes(
  data: Uint8Array<ArrayBuffer>,
  begin = 0,
  end = data.length,
): Box[] {
  const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
  const result: Box[] = [];
  for (let start = begin; start < end;) {
    if (start + 8 > end) throw new Error("Incomplete MP4 box");
    const size = view.getUint32(start);
    if (size < 8 || start + size > end) throw new Error("Invalid MP4 box size");
    result.push({
      type: String.fromCharCode(...data.subarray(start + 4, start + 8)),
      start,
      body: start + 8,
      end: start + size,
    });
    start += size;
  }
  return result;
}

/** Read the AVC decoder configuration from the initialization segment's video track. */
function configuration(
  data: Uint8Array<ArrayBuffer>,
  moov: Box,
): VideoDecoderConfig | null {
  for (const trak of boxes(data, moov.body, moov.end).filter(
    (box) => box.type === "trak",
  )) {
    let current = trak;
    for (const type of ["mdia", "minf", "stbl", "stsd"]) {
      const child = boxes(data, current.body, current.end).find(
        (box) => box.type === type,
      );
      if (!child) break;
      current = child;
    }
    if (current.type !== "stsd") continue;
    for (const entry of boxes(data, current.body + 8, current.end)) {
      if (entry.type !== "avc1") continue;
      // The decoder configuration follows the fixed 78-byte VisualSampleEntry header.
      const avcc = boxes(data, entry.body + 78, entry.end).find(
        (box) => box.type === "avcC",
      );
      if (!avcc) throw new Error("AVC sample entry has no avcC");
      const description = data.slice(avcc.body, avcc.end);
      const codec =
        "avc1." +
        Array.from(description.subarray(1, 4))
          .map((value) => value.toString(16).padStart(2, "0"))
          .join("");
      return { codec, description };
    }
  }
  return null;
}

/**
 * Acquire frames before browser presentation can drop them during accelerated playback.
 * Use the video element up to 1.25x and supplement it with WebCodecs above that rate.
 * The video element owns audio and playback time in both paths.
 * Accept only fMP4 generated by the mpeg2toh264 muxer.
 */
export class EncodedVideoFrames {
  readonly #video: HTMLVideoElement;
  #config: VideoDecoderConfig | null = null;
  #decoderConfig: VideoDecoderConfig | null = null;
  /** Compressed frames within the MSE buffer, retained at normal speed for seeks and later accelerated playback. */
  #samples: Sample[] = [];
  #cursor = 0;
  #decoder: VideoDecoder | null = null;
  #frames: VideoFrame[] = [];
  /** Timestamps of one-tick duplicate pictures needed only as open-GOP decoding references. */
  #short = new Set<number>();
  #ended = false;
  #flushing = false;
  #failed = false;
  #active = false;
  #primed = false;
  #supported = new WeakMap<VideoDecoderConfig, boolean>();

  constructor(video: HTMLVideoElement) {
    this.#video = video;
    video.addEventListener("seeking", this.#seek);
    video.addEventListener("ratechange", this.#seek);
  }

  get active(): boolean {
    return this.#active;
  }

  /** Receive input in MSE append order; the caller retains ownership of the original ArrayBuffer. */
  append(buffer: ArrayBuffer): void {
    if (this.#failed) return;
    const data = new Uint8Array(buffer);
    const view = new DataView(buffer);
    try {
      for (const box of boxes(data)) {
        if (box.type === "moov") {
          this.#config = configuration(data, box);
          const config = this.#config;
          if (config)
            void VideoDecoder.isConfigSupported(config)
              .then((result) => {
                this.#supported.set(config, result.supported === true);
              })
              .catch((error) => this.#fail(error));
        }
        if (box.type !== "moof" || this.#config === null) continue;
        for (const traf of boxes(data, box.body, box.end).filter(
          (child) => child.type === "traf",
        )) {
          const children = boxes(data, traf.body, traf.end);
          const tfhd = children.find((child) => child.type === "tfhd");
          // The muxer places video on track 1 and audio on track 2.
          if (!tfhd || view.getUint32(tfhd.body + 4) !== 1) continue;
          const tfdt = children.find((child) => child.type === "tfdt");
          const trun = children.find((child) => child.type === "trun");
          if (
            !tfdt ||
            !trun ||
            view.getUint32(tfdt.body) !== 0x01000000 ||
            view.getUint32(trun.body) !== 0x01000f01
          )
            throw new Error("Unexpected mpeg2toh264 video fragment layout");
          let decodeTime = Number(view.getBigUint64(tfdt.body + 4));
          let position = box.start + view.getInt32(trun.body + 8);
          const count = view.getUint32(trun.body + 4);
          if (trun.body + 12 + count * 16 > trun.end)
            throw new Error("Incomplete video samples");
          for (let index = 0; index < count; index++) {
            const at = trun.body + 12 + index * 16;
            const duration = view.getUint32(at);
            const size = view.getUint32(at + 4);
            const flags = view.getUint32(at + 8);
            const offset = view.getInt32(at + 12);
            if (position < 0 || position + size > data.length)
              throw new Error("Video sample outside fragment");
            this.#samples.push({
              config: this.#config,
              decodeTime: decodeTime / 90000,
              timestamp: Math.round(((decodeTime + offset) * 1e6) / 90000),
              duration: Math.round((duration * 1e6) / 90000),
              type: flags & 0x10000 ? "delta" : "key",
              data: data.subarray(position, position + size),
            });
            decodeTime += duration;
            position += size;
          }
        }
      }
      // Match the MSE buffer, retaining the preceding keyframe needed to resume decoding.
      const buffered = this.#video.buffered;
      if (buffered.length > 0) {
        let retain = 0;
        for (
          let index = 0;
          index < (this.#active ? this.#cursor : this.#samples.length);
          index++
        ) {
          const sample = this.#samples[index]!;
          if (
            sample.type === "key" &&
            sample.timestamp / 1e6 <= buffered.start(0)
          )
            retain = index;
        }
        if (retain > 0) {
          this.#samples.splice(0, retain);
          this.#cursor = Math.max(0, this.#cursor - retain);
        }
      }
    } catch (error) {
      this.#fail(error);
    }
  }

  /** Return undefined to use the video element, or null to wait for the next decoded frame. */
  take(): VideoFrame | null | undefined {
    if (
      this.#failed ||
      this.#video.playbackRate <= 1.25 ||
      this.#config === null ||
      this.#supported.get(this.#config) !== true
    ) {
      if (this.#active) this.#seek();
      return undefined;
    }
    if (!this.#active) {
      this.#seek();
      this.#active = true;
    }
    const time = this.#video.currentTime;
    try {
      while (
        this.#cursor < this.#samples.length &&
        (this.#decoder?.decodeQueueSize ?? 0) < 6 &&
        this.#frames.length < 12
      ) {
        const sample = this.#samples[this.#cursor]!;
        if (sample.decodeTime > time + 0.25) break;
        if (this.#decoderConfig !== sample.config) {
          if (this.#decoder) {
            // Flush the previous configuration's final B-frames before switching resolution or other settings.
            if (!this.#flushing) {
              this.#flushing = true;
              const decoder = this.#decoder;
              void decoder
                .flush()
                .then(() => {
                  if (this.#decoder !== decoder) return;
                  decoder.close();
                  this.#decoder = null;
                  this.#decoderConfig = null;
                  this.#flushing = false;
                })
                .catch((error) => {
                  if (this.#decoder === decoder) this.#fail(error);
                });
            }
            break;
          }
          const decoder = new VideoDecoder({
            output: (frame) => {
              // Discard frames from a decoder replaced by a seek or configuration change.
              if (this.#decoder !== decoder) frame.close();
              else this.#output(frame);
            },
            error: (error) => {
              if (this.#decoder === decoder) this.#fail(error);
            },
          });
          this.#decoder = decoder;
          this.#decoder.configure(sample.config);
          this.#decoderConfig = sample.config;
        }
        // Decode open-GOP reference pictures, but do not display duplicates with a one-tick duration.
        if ((sample.duration ?? 0) < 1000) this.#short.add(sample.timestamp);
        this.#decoder!.decode(new EncodedVideoChunk(sample));
        this.#cursor++;
      }
      if (
        this.#ended &&
        this.#cursor === this.#samples.length &&
        this.#decoder &&
        !this.#flushing
      ) {
        this.#flushing = true;
        const decoder = this.#decoder;
        void decoder.flush().catch((error) => {
          if (this.#decoder === decoder) this.#fail(error);
        });
      }
    } catch (error) {
      // configure/decode can throw synchronously; fall back to the video element without stopping acquisition.
      this.#fail(error);
      return undefined;
    }
    const frame = this.#frames[0];
    if (
      !frame ||
      frame.timestamp / 1e6 > time + 0.003 * this.#video.playbackRate
    )
      return this.#primed ? null : undefined;
    this.#primed = true;
    return this.#frames.shift()!;
  }

  #output = (frame: VideoFrame): void => {
    if (
      this.#short.delete(frame.timestamp) ||
      frame.timestamp / 1e6 <
        this.#video.currentTime - (this.#primed ? 0.1 : 0.04)
    )
      frame.close();
    else this.#frames.push(frame);
  };

  #seek = (): void => {
    if (this.#decoder && this.#decoder.state !== "closed")
      this.#decoder.close();
    this.#decoder = null;
    this.#decoderConfig = null;
    for (const frame of this.#frames) frame.close();
    this.#frames = [];
    this.#short.clear();
    this.#flushing = false;
    this.#active = false;
    this.#primed = false;
    this.#cursor = 0;
    for (let index = 0; index < this.#samples.length; index++) {
      const sample = this.#samples[index]!;
      if (
        sample.type === "key" &&
        sample.timestamp / 1e6 <= this.#video.currentTime
      )
        this.#cursor = index;
    }
  };

  finish(): void {
    this.#ended = true;
  }

  /** Release the decoder and undisplayed frames while the filter is stopped. */
  suspend(): void {
    this.#seek();
  }

  reset(): void {
    this.#seek();
    this.#samples = [];
    this.#cursor = 0;
    this.#config = null;
    this.#ended = false;
    this.#failed = false;
  }

  destroy(): void {
    this.reset();
    this.#video.removeEventListener("seeking", this.#seek);
    this.#video.removeEventListener("ratechange", this.#seek);
  }

  #fail(error: unknown): void {
    this.#seek();
    this.#failed = true;
    console.warn("mpeg2toh264: decoded video input unavailable", error);
  }
}
