//! H.264 CAVLC codeword tables (Tables 9-5 to 9-10).
//!
//! GENERATED by tools/gen-cavlc.py from the text of ITU-T H.264 (08/2021). Do
//! not edit by hand; regenerate instead. The generator still emits TypeScript,
//! so regenerating today means porting its emitter first.
//!
//! These map values to codewords, since this project only encodes H.264.

/// One codeword: `len` bits whose value is `bits`, most significant first.
#[derive(Clone, Copy, Debug)]
pub struct Vlc {
    pub len: u32,
    pub bits: u32,
}

/// coeff_token, one table per nC range; index with [`coeff_token_table_index`].
/// Within a table the index is `trailing_ones * 17 + total_coeff`.
pub static COEFF_TOKEN: [[Option<Vlc>; 68]; 6] = [
    [
        Some(Vlc { len: 1, bits: 0b1 }),
        Some(Vlc {
            len: 6,
            bits: 0b000101,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00000111,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000111,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000111,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000000111,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001111,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001011,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001000,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000001111,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000001011,
        }),
        Some(Vlc {
            len: 15,
            bits: 0b000000000001111,
        }),
        Some(Vlc {
            len: 15,
            bits: 0b000000000001011,
        }),
        Some(Vlc {
            len: 16,
            bits: 0b0000000000001111,
        }),
        Some(Vlc {
            len: 16,
            bits: 0b0000000000001011,
        }),
        Some(Vlc {
            len: 16,
            bits: 0b0000000000000111,
        }),
        Some(Vlc {
            len: 16,
            bits: 0b0000000000000100,
        }),
        None,
        Some(Vlc { len: 2, bits: 0b01 }),
        Some(Vlc {
            len: 6,
            bits: 0b000100,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00000110,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000110,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000110,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000000110,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001110,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001010,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000001110,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000001010,
        }),
        Some(Vlc {
            len: 15,
            bits: 0b000000000001110,
        }),
        Some(Vlc {
            len: 15,
            bits: 0b000000000001010,
        }),
        Some(Vlc {
            len: 15,
            bits: 0b000000000000001,
        }),
        Some(Vlc {
            len: 16,
            bits: 0b0000000000001110,
        }),
        Some(Vlc {
            len: 16,
            bits: 0b0000000000001010,
        }),
        Some(Vlc {
            len: 16,
            bits: 0b0000000000000110,
        }),
        None,
        None,
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0000101,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00000101,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000101,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000101,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000000101,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001101,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001001,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000001101,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000001001,
        }),
        Some(Vlc {
            len: 15,
            bits: 0b000000000001101,
        }),
        Some(Vlc {
            len: 15,
            bits: 0b000000000001001,
        }),
        Some(Vlc {
            len: 16,
            bits: 0b0000000000001101,
        }),
        Some(Vlc {
            len: 16,
            bits: 0b0000000000001001,
        }),
        Some(Vlc {
            len: 16,
            bits: 0b0000000000000101,
        }),
        None,
        None,
        None,
        Some(Vlc {
            len: 5,
            bits: 0b00011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000011,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0000100,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00000100,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000100,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000100,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000000100,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001100,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000001100,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000001000,
        }),
        Some(Vlc {
            len: 15,
            bits: 0b000000000001100,
        }),
        Some(Vlc {
            len: 15,
            bits: 0b000000000001000,
        }),
        Some(Vlc {
            len: 16,
            bits: 0b0000000000001100,
        }),
        Some(Vlc {
            len: 16,
            bits: 0b0000000000001000,
        }),
    ],
    [
        Some(Vlc { len: 2, bits: 0b11 }),
        Some(Vlc {
            len: 6,
            bits: 0b001011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000111,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0000111,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00000111,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00000100,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000111,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000001111,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000001011,
        }),
        Some(Vlc {
            len: 12,
            bits: 0b000000001111,
        }),
        Some(Vlc {
            len: 12,
            bits: 0b000000001011,
        }),
        Some(Vlc {
            len: 12,
            bits: 0b000000001000,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001111,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001011,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000000111,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000001001,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000000111,
        }),
        None,
        Some(Vlc { len: 2, bits: 0b10 }),
        Some(Vlc {
            len: 5,
            bits: 0b00111,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001010,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000110,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0000110,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00000110,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000110,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000001110,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000001010,
        }),
        Some(Vlc {
            len: 12,
            bits: 0b000000001110,
        }),
        Some(Vlc {
            len: 12,
            bits: 0b000000001010,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001110,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001010,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000001011,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000001000,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000000110,
        }),
        None,
        None,
        Some(Vlc {
            len: 3,
            bits: 0b011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000101,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0000101,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00000101,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000101,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000001101,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000001001,
        }),
        Some(Vlc {
            len: 12,
            bits: 0b000000001101,
        }),
        Some(Vlc {
            len: 12,
            bits: 0b000000001001,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001101,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001001,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000000110,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000001010,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000000101,
        }),
        None,
        None,
        None,
        Some(Vlc {
            len: 4,
            bits: 0b0101,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0100,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00110,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001000,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000100,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0000100,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000100,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000001100,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000001000,
        }),
        Some(Vlc {
            len: 12,
            bits: 0b000000001100,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001100,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000001000,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000000001,
        }),
        Some(Vlc {
            len: 14,
            bits: 0b00000000000100,
        }),
    ],
    [
        Some(Vlc {
            len: 4,
            bits: 0b1111,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001111,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001000,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001111,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001011,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001001,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001000,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00001111,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00001011,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000001111,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000001011,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000001000,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000001101,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000001001,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000101,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000001,
        }),
        None,
        Some(Vlc {
            len: 4,
            bits: 0b1110,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b01111,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b01100,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b01010,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b01000,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001110,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001010,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001110,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00001110,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00001010,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000001110,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000001010,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000111,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000001100,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000001000,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000100,
        }),
        None,
        None,
        Some(Vlc {
            len: 4,
            bits: 0b1101,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b01110,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b01011,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b01001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001101,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001001,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001101,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001010,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00001101,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00001001,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000001101,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000001001,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000001011,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000111,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000011,
        }),
        None,
        None,
        None,
        Some(Vlc {
            len: 4,
            bits: 0b1100,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b1011,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b1010,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b1001,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b1000,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b01101,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001100,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001100,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00001100,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00001000,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000001100,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000001010,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000110,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000010,
        }),
    ],
    [
        Some(Vlc {
            len: 6,
            bits: 0b000011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000000,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000100,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001000,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001100,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b010000,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b010100,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b011000,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b011100,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b100000,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b100100,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b101000,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b101100,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b110000,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b110100,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b111000,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b111100,
        }),
        None,
        Some(Vlc {
            len: 6,
            bits: 0b000001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000101,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001101,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b010001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b010101,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b011001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b011101,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b100001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b100101,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b101001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b101101,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b110001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b110101,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b111001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b111101,
        }),
        None,
        None,
        Some(Vlc {
            len: 6,
            bits: 0b000110,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001010,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001110,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b010010,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b010110,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b011010,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b011110,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b100010,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b100110,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b101010,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b101110,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b110010,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b110110,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b111010,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b111110,
        }),
        None,
        None,
        None,
        Some(Vlc {
            len: 6,
            bits: 0b001011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b001111,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b010011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b010111,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b011011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b011111,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b100011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b100111,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b101011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b101111,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b110011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b110111,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b111011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b111111,
        }),
    ],
    [
        Some(Vlc { len: 2, bits: 0b01 }),
        Some(Vlc {
            len: 6,
            bits: 0b000111,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000100,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000010,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some(Vlc { len: 1, bits: 0b1 }),
        Some(Vlc {
            len: 6,
            bits: 0b000110,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0000011,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00000011,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0000010,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00000010,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some(Vlc {
            len: 6,
            bits: 0b000101,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0000000,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    [
        Some(Vlc { len: 1, bits: 0b1 }),
        Some(Vlc {
            len: 7,
            bits: 0b0001111,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001110,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000111,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000110,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000111,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000000111,
        }),
        Some(Vlc {
            len: 12,
            bits: 0b000000000111,
        }),
        Some(Vlc {
            len: 13,
            bits: 0b0000000000111,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some(Vlc { len: 2, bits: 0b01 }),
        Some(Vlc {
            len: 7,
            bits: 0b0001101,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001100,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000101,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000110,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000000110,
        }),
        Some(Vlc {
            len: 12,
            bits: 0b000000000110,
        }),
        Some(Vlc {
            len: 12,
            bits: 0b000000000101,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001011,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001010,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000100,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000101,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000000101,
        }),
        Some(Vlc {
            len: 12,
            bits: 0b000000000100,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        Some(Vlc {
            len: 5,
            bits: 0b00001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000001,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001001,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0001000,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000100,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000000100,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
];

/// Select the coeff_token table for a given nC (clause 9.2.1).
pub fn coeff_token_table_index(n_c: i32) -> usize {
    match n_c {
        -1 => 4, // chroma DC, 4:2:0
        -2 => 5, // chroma DC, 4:2:2
        n if n < 2 => 0,
        n if n < 4 => 1,
        n if n < 8 => 2,
        _ => 3,
    }
}

/// total_zeros for 4x4 blocks, indexed by `tz_vlc_index - 1` then by total_zeros.
pub static TOTAL_ZEROS_4X4: [&[Option<Vlc>]; 15] = [
    &[
        Some(Vlc { len: 1, bits: 0b1 }),
        Some(Vlc {
            len: 3,
            bits: 0b011,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b010,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0011,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0010,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00011,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00010,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000010,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0000011,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0000010,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00000011,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00000010,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000011,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000010,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000001,
        }),
    ],
    &[
        Some(Vlc {
            len: 3,
            bits: 0b111,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b110,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b101,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b100,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b011,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0101,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0100,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0011,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0010,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00011,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00010,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000011,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000010,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000000,
        }),
        None,
    ],
    &[
        Some(Vlc {
            len: 4,
            bits: 0b0101,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b111,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b110,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b101,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0100,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0011,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b100,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b011,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0010,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00011,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00010,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000001,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000000,
        }),
        None,
        None,
    ],
    &[
        Some(Vlc {
            len: 5,
            bits: 0b00011,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b111,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0101,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0100,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b110,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b101,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b100,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0011,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b011,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0010,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00010,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00001,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00000,
        }),
        None,
        None,
        None,
    ],
    &[
        Some(Vlc {
            len: 4,
            bits: 0b0101,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0100,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0011,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b111,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b110,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b101,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b100,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b011,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0010,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00001,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0001,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00000,
        }),
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc {
            len: 6,
            bits: 0b000001,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00001,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b111,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b110,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b101,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b100,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b011,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b010,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0001,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000000,
        }),
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc {
            len: 6,
            bits: 0b000001,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00001,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b101,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b100,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b011,
        }),
        Some(Vlc { len: 2, bits: 0b11 }),
        Some(Vlc {
            len: 3,
            bits: 0b010,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0001,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000000,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc {
            len: 6,
            bits: 0b000001,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0001,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00001,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b011,
        }),
        Some(Vlc { len: 2, bits: 0b11 }),
        Some(Vlc { len: 2, bits: 0b10 }),
        Some(Vlc {
            len: 3,
            bits: 0b010,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000000,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc {
            len: 6,
            bits: 0b000001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000000,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0001,
        }),
        Some(Vlc { len: 2, bits: 0b11 }),
        Some(Vlc { len: 2, bits: 0b10 }),
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc { len: 2, bits: 0b01 }),
        Some(Vlc {
            len: 5,
            bits: 0b00001,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc {
            len: 5,
            bits: 0b00001,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00000,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc { len: 2, bits: 0b11 }),
        Some(Vlc { len: 2, bits: 0b10 }),
        Some(Vlc { len: 2, bits: 0b01 }),
        Some(Vlc {
            len: 4,
            bits: 0b0001,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc {
            len: 4,
            bits: 0b0000,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0001,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b010,
        }),
        Some(Vlc { len: 1, bits: 0b1 }),
        Some(Vlc {
            len: 3,
            bits: 0b011,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc {
            len: 4,
            bits: 0b0000,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0001,
        }),
        Some(Vlc { len: 2, bits: 0b01 }),
        Some(Vlc { len: 1, bits: 0b1 }),
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc {
            len: 3,
            bits: 0b000,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc { len: 1, bits: 0b1 }),
        Some(Vlc { len: 2, bits: 0b01 }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc { len: 2, bits: 0b00 }),
        Some(Vlc { len: 2, bits: 0b01 }),
        Some(Vlc { len: 1, bits: 0b1 }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc { len: 1, bits: 0b0 }),
        Some(Vlc { len: 1, bits: 0b1 }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
];

/// total_zeros for the 2x2 chroma DC block of 4:2:0, indexed by `tz_vlc_index - 1`.
pub static TOTAL_ZEROS_CHROMA_DC: [&[Option<Vlc>]; 3] = [
    &[
        Some(Vlc { len: 1, bits: 0b1 }),
        Some(Vlc { len: 2, bits: 0b01 }),
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b000,
        }),
    ],
    &[
        Some(Vlc { len: 1, bits: 0b1 }),
        Some(Vlc { len: 2, bits: 0b01 }),
        Some(Vlc { len: 2, bits: 0b00 }),
        None,
    ],
    &[
        Some(Vlc { len: 1, bits: 0b1 }),
        Some(Vlc { len: 1, bits: 0b0 }),
        None,
        None,
    ],
];

/// run_before, indexed by `min(zeros_left, 7) - 1` then by run_before. The last
/// entry serves every zeros_left above 6.
pub static RUN_BEFORE: [&[Option<Vlc>]; 7] = [
    &[
        Some(Vlc { len: 1, bits: 0b1 }),
        Some(Vlc { len: 1, bits: 0b0 }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc { len: 1, bits: 0b1 }),
        Some(Vlc { len: 2, bits: 0b01 }),
        Some(Vlc { len: 2, bits: 0b00 }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc { len: 2, bits: 0b11 }),
        Some(Vlc { len: 2, bits: 0b10 }),
        Some(Vlc { len: 2, bits: 0b01 }),
        Some(Vlc { len: 2, bits: 0b00 }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc { len: 2, bits: 0b11 }),
        Some(Vlc { len: 2, bits: 0b10 }),
        Some(Vlc { len: 2, bits: 0b01 }),
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b000,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc { len: 2, bits: 0b11 }),
        Some(Vlc { len: 2, bits: 0b10 }),
        Some(Vlc {
            len: 3,
            bits: 0b011,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b010,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b000,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc { len: 2, bits: 0b11 }),
        Some(Vlc {
            len: 3,
            bits: 0b000,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b011,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b010,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b101,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b100,
        }),
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    &[
        Some(Vlc {
            len: 3,
            bits: 0b111,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b110,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b101,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b100,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b011,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b010,
        }),
        Some(Vlc {
            len: 3,
            bits: 0b001,
        }),
        Some(Vlc {
            len: 4,
            bits: 0b0001,
        }),
        Some(Vlc {
            len: 5,
            bits: 0b00001,
        }),
        Some(Vlc {
            len: 6,
            bits: 0b000001,
        }),
        Some(Vlc {
            len: 7,
            bits: 0b0000001,
        }),
        Some(Vlc {
            len: 8,
            bits: 0b00000001,
        }),
        Some(Vlc {
            len: 9,
            bits: 0b000000001,
        }),
        Some(Vlc {
            len: 10,
            bits: 0b0000000001,
        }),
        Some(Vlc {
            len: 11,
            bits: 0b00000000001,
        }),
    ],
];

/// Table 9-4(a): coded_block_pattern to codeNum for 4:2:0 and 4:2:2, intra.
pub static CBP_TO_CODE_NUM_INTRA: [u32; 48] = [
    3, 29, 30, 17, 31, 18, 37, 8, 32, 38, 19, 9, 20, 10, 11, 2, 16, 33, 34, 21, 35, 22, 39, 4, 36,
    40, 23, 5, 24, 6, 7, 1, 41, 42, 43, 25, 44, 26, 46, 12, 45, 47, 27, 13, 28, 14, 15, 0,
];
/// Table 9-4(a), inter macroblocks, which use a different ordering.
pub static CBP_TO_CODE_NUM_INTER: [u32; 48] = [
    0, 2, 3, 7, 4, 8, 17, 13, 5, 18, 9, 14, 10, 15, 16, 11, 1, 32, 33, 36, 34, 37, 44, 40, 35, 45,
    38, 41, 39, 42, 43, 19, 6, 24, 25, 20, 26, 21, 46, 28, 27, 47, 22, 29, 23, 30, 31, 12,
];
