/**
 * The clip the decoder is asked about, as a data URL.
 *
 * Six frames of 1440x1080 interlaced H.264, top field first, whose two fields
 * are the opposite of each other: one is bright, the other is dark, and which
 * is which swaps every frame. Woven, that is a picture of alternating lines
 * that inverts thirty times a second -- the most combing a frame can hold, and
 * motion in every pixel of it, so that a deinterlacer of any kind has to do
 * something to it and a decoder that leaves it alone leaves the pattern exact.
 *
 * The size is the point of it and not an accident: a decoder picks its path by
 * what it is decoding, and a thumbnail-sized clip could take a different one
 * to the broadcast this player exists for. It is the same shape as one, and it
 * still costs less than five kilobytes, because a pattern this regular is
 * nothing to an encoder.
 *
 * Regenerate with ffmpeg:
 *
 * ```
 * ffmpeg -f lavfi -i "nullsrc=s=1440x1080:r=30000/1001:d=0.2" \
 *   -vf "geq=lum='if(mod(Y+N,2),235,16)':cb=128:cr=128,format=yuv420p,\
 *        setparams=field_mode=tff" \
 *   -c:v libx264 -preset veryslow -crf 8 -flags +ilme+ildct \
 *   -x264-params "interlaced=1:tff=1:keyint=30" -movflags +faststart probe.mp4
 * ```
 */
export const PROBE_CLIP =
  "data:video/mp4;base64," +
  "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAN8bW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAAMkAAQAA" +
  "AQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAgAAAqd0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAAMkAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA" +
  "AAAAAAABAAAAAAAAAAAAAAAAAABAAAAABaAAAAQ4AAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAADJAAAH0gABAAAAAAIf" +
  "bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAB1MAAAF3ZVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRl" +
  "b0hhbmRsZXIAAAABym1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAA" +
  "AQAAAYpzdGJsAAAAwnN0c2QAAAAAAAAAAQAAALJhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAABaAEOABIAAAASAAAAAAA" +
  "AAABFUxhdmM2MS4xOS4xMDEgbGlieDI2NAAAAAAAAAAAAAAAGP//AAAAOGF2Y0MBZAA+/+EAGmdkAD6scgRAWgRP3gIgAAB9" +
  "IAAdTAPjx7CMAQAHaPhCgSyyLP34+AAAAAAQcGFzcAAAAAEAAAABAAAAFGJ0cnQAAAAAAAGk1AAAAAAAAAAYc3R0cwAAAAAA" +
  "AAABAAAABgAAA+kAAAAUc3RzcwAAAAAAAAABAAAAAQAAADhjdHRzAAAAAAAAAAUAAAABAAAH0gAAAAEAABd2AAAAAQAAB9IA" +
  "AAABAAAAAAAAAAIAAAPpAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAAGAAAAAQAAACxzdHN6AAAAAAAAAAAAAAAGAAAEKQAAAfwA" +
  "AAHbAAACAAAAAEQAAABEAAAAFHN0Y28AAAAAAAAAAQAAA6wAAABhdWR0YQAAAFltZXRhAAAAAAAAACFoZGxyAAAAAAAAAABt" +
  "ZGlyYXBwbAAAAAAAAAAAAAAAACxpbHN0AAAAJKl0b28AAAAcZGF0YQAAAAEAAAAATGF2ZjYxLjcuMTAwAAAACGZyZWUAAAqQ" +
  "bWRhdAAAArAGBf//rNxF6b3m2Ui3lizYINkj7u94MjY0IC0gY29yZSAxNjQgcjMxMDggMzFlMTlmOSAtIEguMjY0L01QRUct" +
  "NCBBVkMgY29kZWMgLSBDb3B5bGVmdCAyMDAzLTIwMjMgLSBodHRwOi8vd3d3LnZpZGVvbGFuLm9yZy94MjY0Lmh0bWwgLSBv" +
  "cHRpb25zOiBjYWJhYz0xIHJlZj0xNiBkZWJsb2NrPTE6MDowIGFuYWx5c2U9MHgzOjB4MTMzIG1lPXVtaCBzdWJtZT0xMCBw" +
  "c3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0xIG1lX3JhbmdlPTI0IGNocm9tYV9tZT0xIHRyZWxsaXM9MiA4eDhk" +
  "Y3Q9MSBjcW09MCBkZWFkem9uZT0yMSwxMSBmYXN0X3Bza2lwPTEgY2hyb21hX3FwX29mZnNldD0tMiB0aHJlYWRzPTE1IGxv" +
  "b2thaGVhZF90aHJlYWRzPTIgc2xpY2VkX3RocmVhZHM9MCBucj0wIGRlY2ltYXRlPTEgaW50ZXJsYWNlZD10ZmYgYmx1cmF5" +
  "X2NvbXBhdD0wIGNvbnN0cmFpbmVkX2ludHJhPTAgYmZyYW1lcz04IGJfcHlyYW1pZD0yIGJfYWRhcHQ9MiBiX2JpYXM9MCBk" +
  "aXJlY3Q9MyB3ZWlnaHRiPTEgb3Blbl9nb3A9MCB3ZWlnaHRwPTAga2V5aW50PTMwIGtleWludF9taW49MyBzY2VuZWN1dD00" +
  "MCBpbnRyYV9yZWZyZXNoPTAgcmNfbG9va2FoZWFkPTMwIHJjPWNyZiBtYnRyZWU9MSBjcmY9OC4wIHFjb21wPTAuNjAgcXBt" +
  "aW49MCBxcG1heD02OSBxcHN0ZXA9NCBpcF9yYXRpbz0xLjQwIGFxPTE6MS4wMACAAAAABQYBATKAAAABaGWIgIBAR//+/76i" +
  "vgU3edyfbbnP6kzu1BfFPXa9rMu/FCi/GMk76JT20AAAAwAAAwAAAwAAAwAAAwAAAwEJmrWZnq7KhXxVTgAAAwAAAwAAAwAA" +
  "BJ9gAAADAAAKtgAAAwAAAwCi4AAAAwAAHQgAAAMAAAiqAAADAAADA7EAAAMAAAMCCgAAAwAAAwAAAwAAAwAAAwAAAwAAAwAA" +
  "AwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAA" +
  "AwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAA" +
  "AwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAL+QAAAAUGAQEygAAA" +
  "Ae9BmghSyEf/2XyP/Fn/6mXyw21/v4X7ly3FFO60AAADAAADAAADAAADAAADAAADAAADAB+zQAAAAwAAAwAAAwAATLAAAAMA" +
  "AAMAAAMAAW4AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMA" +
  "AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMA" +
  "AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMA" +
  "AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMA" +
  "AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMA" +
  "AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAy4AAAAFBgEB" +
  "MoAAAAHOQZ4QInEI//Wd4/6LqH4G30AC1/Y4D6hTuCgMq8YAAAMAAAMAAAMAAAMAAAMAAAMAAAMAOdrAAAADAAADAAADAnRQ" +
  "AAADAAADAAADAq+AAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAAD" +
  "AAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAAD" +
  "AAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAAD" +
  "AAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAAD" +
  "AAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAAD" +
  "AAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAObAAAABQYBATKAAAAB8wGeGBJohH/1klH/XMf/q8vmp5I5OYBI" +
  "V1CU5tb7hgAAAwAAAwAAAwAAAwAAAwAAAwAAAwAADG8QAAADAAADAAADAAATjAAAAwAAAwAAAwAAW4AAAAMAAAMAAAMAAAMA" +
  "AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMA" +
  "AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMA" +
  "AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMA" +
  "AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMA" +
  "AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMA" +
  "AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAy4AAAAAFBgEBMoAAAAA3AZ4YMtSEf/V+v/1vEP/Z" +
  "gAEtQAAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwBnQQAAAAUGAQEygAAAADcBnhhC1IR/9W1x/xHp//qwAC54" +
  "AAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADADfh";
